### ISSUE TITLE
Backups - Can't find them on Android

### ISSUE THREAD

**Issue by Danielrc15** [crobertsbmw/MyTargets#11]
Hi,

I have backups on my phone, I am currently switching phones. But where the data should be, it's not. I even created the folders required. Still nothing. I also tried to backup to Google Drive and signed into Google Drive but it never backs up.

Can you tell me the best way to move my data from one phone to the other?

Or just the location of where the files should be on the phone?

Thanks

Daniel

**Comment by inquisitivenoodle** [comment]
I'm having the same issue. Did you find any resolution ?

**Comment by Danielrc15** [comment]
Hi,

No, but they did reply and say they don’t know when it will be fixed. Keep your old phone for the time being. Don’t think I will do that though.

I did do a video on it though: https://youtu.be/82aFS4t-H7E

Thanks

Daniel

**Comment by MikeWilliams-UK** [comment]
Is there any update on this?

I too would like to be able to safely export the backup to another device.

**Comment by MikeWilliams-UK** [comment]
Just been watching that video @Danielrc15 I even tried the backup to Google Drive and that did not ever complete.

**Comment by MikeWilliams-UK** [comment]
After selecting a Google Drive account I can't select a different google account, even after removing app permissions.

It is also not possible to restore a backup (after messing up something) as you can't select the backup to restore from.

Therefore the backup facility turns out to be as useful as the proverbial "Chocolate Teapot".

**Comment by Danielrc15** [comment]
Oh yeah you are on your own really when it comes to trying to backup. All you can do really is export your scores as individual PDF’s and store them.

I started fresh again on my new phone, all my scores had been recorded in my clubs database anyway.

**Comment by MikeWilliams-UK** [comment]
Sharing the pdf directly to my OneDrive works nicely.

**Comment by crankyoldgit** [comment]
+1 for this problem to be fixed. I've got three years of data (about 40k arrows) invested in this app. My phone is slowly dying and I need to replace it soon.

**Comment by jatkinson1000** [comment]
I assume the latest update on Google Play fixes this issue @guyandtheworld ?
