### ISSUE TITLE
Unable to grant Storage Permissions to app - Pixel 7, v3.2.5

### ISSUE THREAD

**Issue by corey-richardson** [crobertsbmw/MyTargets#14]
Recently moved over to the Pixel 7 from the Pixel 5 with a backup saved on Google Drive, but can't access it.

Settings -> Backup brings up a dialogue box "Permission Required" with instructions on how to grant this permission however the Storage permission does not appear in this menu.

Allowed: Camera, Contacts, Location
Not allowed: No permissions denied

**Comment by corey-richardson** [comment]
![Screenshot_20230424-145910.png](https://user-images.githubusercontent.com/16747709/234020037-cf47ed04-b856-4852-b5fa-1a545d4c7d0b.png)

![Screenshot_20230424-145919.png](https://user-images.githubusercontent.com/16747709/234020051-37cc18e9-aadc-4be2-94d7-3473560b9379.png)

**Comment by Reddax** [comment]
I've got the same issue on my Samsung S22

**Comment by bruno-ramos** [comment]
I've got the exactly same issue on my Asus Zenfone 9 (Android 13).
I did a clean installation (version 3.2.5) from Google Play.

**Comment by jatkinson1000** [comment]
@guyandtheworld @roshanrai06 Did PR #17 or #18 address this?

**Comment by roshanrai06** [comment]
> @guyandtheworld @roshanrai06 Did PR #17 or #18 address this?

 This issue is fixed in the latest update
